[package]
edition = "2021"
name = "test-utils"
version = "0.1.0"


[dependencies]
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.0.0" }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.0.0" }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.0.0" }
scrypto-unit = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.0.0" }
home = "0.5.5"
getrandom = { version = "0.2", features = ["js"] }

[dev-dependencies]


[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
doctest = false