[package]
edition = "2021"
name = "random"
version = "0.1.0"


[dependencies]

[dev-dependencies]
random = { path = ".", features = ["test"] }


[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
path = "src/random.rs"

